### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jpietrangelo** [ioquatix/script-runner#13]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
ScriptRunner.activate (/Users/jmp/.atom/packages/script-runner/lib/script-runner.coffee:26:9)
```

**Comment by ioquatix** [comment]
@huba do you want to take a stab at fixing this?

**Comment by huba** [comment]
Yep, I'll get onto it.

**Comment by huba** [comment]
https://github.com/ioquatix/script-runner/commit/e09ee9a95dfc237946806ed5ba65a01a839f65e7

Turns out we did not actually need the view of workspace here, we needed atom.commands. This should get rid of all the uses of workspaceView. I still need to look into what is going on in https://github.com/ioquatix/script-runner/blob/master/spec/script-runner-spec.coffee so I won't close this issue.

**Comment by huba** [comment]
https://github.com/ioquatix/script-runner/commit/73194233533145c9e9ed606e8202edbf2b2069f9
Everything is fixed. We might want to look into moving our runner view into atom.views.

**Comment by ioquatix** [comment]
Awesome, great work. I'll release an update.
