### ISSUE TITLE
Changing version of python

### ISSUE THREAD

**Issue by hyphen-wrex** [ioquatix/script-runner#48]
Hello, how can I change the version of python that I'm using?

**Comment by huba** [comment]
The best way to do this is to change the shebang line.

**Comment by hyphen-wrex** [comment]
Sorry for not commenting about that in the first place. I meant that atom-runner have a line in atom configuration file to change the python binary to use. Since this package is the fork of atom-runner, I expected it to work the similar way, but found nothing about that in read.me; could you please clarify this to me? Using mac

**Comment by ioquatix** [comment]
@hyphen-wrex We don't support that mode of configuration. The reason is that it is non-standard. It is better to work the same way the rest of the system and shell works, e.g. use `#!/usr/bin/env python2.7` or `#!/usr/bin/env python3.4` etc. This way when you run the script from the command line it will also work correctly. IF you want `python` to default to something, why not set that up in your shell so it also works correctly there?

**Comment by hyphen-wrex** [comment]
@ioquatix That is true indeed; Googled about shebang and setting up python in command line and made it like you exampled; Big Thanks!
