### ISSUE TITLE
running python with selenium 

### ISSUE THREAD

**Issue by m-talha-khan** [ioquatix/script-runner#98]
The problem I am facing is that when the script executed from top to the bottom, the third party selenium driver just stop. everything is working I can launch firefox with selenium but after it launch, 2 second it's close firefox without giving error 

```
# !/usr/bin/env python

from selenium import webdriver

driver = webdriver.Firefox()

driver.get('https://duckduckgo.com/')

```
I could delay firefox from closing by import time but that's not the solution 

I have tired with script {rgbrk} it works fine!
so the problem has to be in scipt-runner

**Comment by ioquatix** [comment]
Don't put a space on the first line between `#` and `!`.

```python
#!/usr/bin/env python

from selenium import webdriver

driver = webdriver.Firefox()

driver.get('https://duckduckgo.com/')

input()
```

Does that work as expected?

**Comment by m-talha-khan** [comment]
Thanks mate that's a awesome trick and it works, I didn't even thought about input :)
The extra space was a copy and paste error

**Comment by ioquatix** [comment]
The reason why `script-runner` "fails" in your original observation is because it's strict about killing all sub-processes. So it also kills the Firefox process. It looks like, at least based on what you said, that `script` doesn't do this this, and so you have the potential to leak processes over time.
